please install this packages

In [1]:
!pip install pycountry

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 10.1 MB 5.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for pycountry: filename=pycountry-22.3.5-py2.py3-none-any.whl size=10681845 sha256=7d73d75bd503c282914d29616c258ddf1ffd7c5f7a571873afc5f6a4f158f06c
  Stored in directory: /root/.cache/pip/wheels/e2/aa/0f/c224e473b464387170b83ca7c66947b4a7e33e8d903a679748
Successfully built pycountry


In [2]:
!pip install googletrans==3.1.0a0 #pip install googletrans==4.0.0-rc1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 55 kB 2.3 MB/s 
     |████████████████████████████████| 1.5 MB 10.5 MB/s 
     |████████████████████████████████| 42 kB 1.2 MB/s 
     |████████████████████████████████| 65 kB 3.5 MB/s 
     |████████████████████████████████| 53 kB 2.1 MB/s 
  Created wheel for googletrans: filename=googletrans-3.1.0a0-py3-none-any.whl size=16368 sha256=e0ba2a6359b353a28059a7d6b209adac714575e7e6787de79898b79164e5f312
  Stored in directory: /root/.cache/pip/wheels/dd/59/af/8d6c96a719763990f1c548e36b17d9efdfb767f42f7ff39f53
Successfully built googletrans


TASK :: Take any newspaper data through their API and classify the sentiment within the articles.

In [3]:
#importing libraries
import requests
import json
import pandas as pd
import pycountry
from googletrans import Translator

In [4]:
#initializing arrays
title=[]
description=[]
publishedAt = []
category = []

In [5]:
categories= ['business','entertainment','health','science','sports','technology']
countries = [country.alpha_2 for country in list(pycountry.countries)] 

In [6]:
1#function for getting data from api
def get_data(con,cat):
  r = requests.get(f"https://newsapi.org/v2/top-headlines?country={con}&category={cat}&apiKey=5d5f3eead563403ca1faad1f3d663c8e")
  data = json.loads(r.content)
  # print(data)
  for i in range(len(data['articles'])):
    title.append(data['articles'][i]['title'])
    description.append(data['articles'][i]['description'])
    publishedAt.append(data['articles'][i]['publishedAt'])
    category.append(cat)

In [7]:
for country in countries:
  for cat in categories:
    try:
      get_data(country,cat) #as countries are not availble in api try except to handle that error
    except:
      continue

In [8]:
df = pd.DataFrame() #creating datafarme

In [9]:
#assigning columns of data frame
df['title']=title
df['description']=description
df['publishedAt'] = publishedAt
df['category']=category

In [10]:
df.head()

title  \
0  أخبار العالم : أسعار الذهب اليوم الإثنين 26 دي...   
1  بعد رفع سعر الفائدة.. سعر الجنيه المصري مقابل ...   
2  عالمي تغليف المشروبات بالبلاستيك سوق قم بتطوير...   
3  عالمي خزانات طبية ببابين سوق قم بتطوير معدل نم...   
4  أخبار التكنولوجيا : تسلا تستعين بشركة TSMC للح...   

                                         description           publishedAt  \
0  أخبار العالم : يرصد التقرير التالي سعر الذهب ا...  2022-12-26T05:51:20Z   
1  (MENAFN - Al-Bayan)  ??? ??? ?????? ?????? ???...  2022-12-26T05:25:29Z   
2  يقدم تقرير Market.us "تغليف المشروبات بالبلاست...  2022-12-26T04:07:57Z   
3                                               None  2022-12-26T02:23:00Z   
4  أخبار التكنولوجيا : كشف تقرير حديث لـ DigiTime...  2022-12-26T02:20:34Z   

   category  
0  business  
1  business  
2  business  
3  business  
4  business

In [11]:
df.tail()

title  \
455  10 Begriffe, die nur echte PC-Profis kennen - ...   
456  Digitalwährungen im Fokus: So bewegen sich Bit...   
457  Das ComputerBase-Weihnachtsrätsel 2022 - Compu...   
458  Vom iPhone zu Android wechseln: So einfach ist...   
459  Mit usenet-crew.com geht bald weiteres Forum a...   

                                           description           publishedAt  \
455                                               None  2022-12-25T08:03:00Z   
456               So bewegen sich Bitcoin & Co. heute.  2022-12-25T07:48:20Z   
457  Dir war das Nikolaus-Rätsel in diesem Jahr nic...  2022-12-25T07:00:00Z   
458  Ob zu Samsung, Xiaomi oder Sony: Der Umzug vom...  2022-12-25T06:56:30Z   
459  In naher Zukunft soll das neue deutschsprachig...  2022-12-25T06:30:28Z   

       category  
455  technology  
456  technology  
457  technology  
458  technology  
459  technology

In [12]:
#we need traslator as many news are not in english so we using google translator for that
translator = Translator()

In [13]:
for i in range(len(df.title)):
  df.title[i] = translator.translate(df.title[i]).text
  df.description[i] = translator.translate(df.description[i]).text

In [14]:
df.head()

title  \
0  World news: Gold prices today, Monday, Decembe...   
1  After raising the interest rate.. the price of...   
2  Global Beverage Packaging Market Develop Stead...   
3  Global 2-Door Medical Cabinets Market Develop ...   
4  Technology news: Tesla is using TSMC to obtain...   

                                         description           publishedAt  \
0  World news: The following report monitors the ...  2022-12-26T05:51:20Z   
1  (Manafen - Al-Bayan) ??? ??? ?????? ?????? ???...  2022-12-26T05:25:29Z   
2  Market.us report “Plastic Beverage Packaging” ...  2022-12-26T04:07:57Z   
3                                                     2022-12-26T02:23:00Z   
4  Technology news: A recent report by DigiTimes ...  2022-12-26T02:20:34Z   

   category  
0  business  
1  business  
2  business  
3  business  
4  business

In [15]:
df.tail()

title  \
455  10 terms that only real PC professionals know ...   
456  Digital currencies in focus: This is how Bitco...   
457  The ComputerBase Christmas Riddle 2022 - Compu...   
458  Switch from iPhone to Android: It's that easy ...   
459  Another forum will soon be launched with usene...   

                                           description           publishedAt  \
455                                                     2022-12-25T08:03:00Z   
456              This is how Bitcoin & Co. move today.  2022-12-25T07:48:20Z   
457  St. Nicholas' riddle wasn't hard enough for yo...  2022-12-25T07:00:00Z   
458  Whether it's Samsung, Xiaomi or Sony: moving f...  2022-12-25T06:56:30Z   
459  In the near future the new German-speaking for...  2022-12-25T06:30:28Z   

       category  
455  technology  
456  technology  
457  technology  
458  technology  
459  technology

In [16]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [17]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


True

In [19]:
for index, row in df['description'].iteritems():
  score = SentimentIntensityAnalyzer().polarity_scores(row)

  neg = score['neg']
  neu = score['neu']
  pos = score['pos']

  if neg > pos :
    df.loc[index,'sentiment'] = "Negative"
  elif pos > neg:
    df.loc[index, 'sentiment'] = "Positive"
  else:
    df.loc[index, 'sentiment'] = "Neutral"

In [20]:
df.head()

title  \
0  World news: Gold prices today, Monday, Decembe...   
1  After raising the interest rate.. the price of...   
2  Global Beverage Packaging Market Develop Stead...   
3  Global 2-Door Medical Cabinets Market Develop ...   
4  Technology news: Tesla is using TSMC to obtain...   

                                         description           publishedAt  \
0  World news: The following report monitors the ...  2022-12-26T05:51:20Z   
1  (Manafen - Al-Bayan) ??? ??? ?????? ?????? ???...  2022-12-26T05:25:29Z   
2  Market.us report “Plastic Beverage Packaging” ...  2022-12-26T04:07:57Z   
3                                                     2022-12-26T02:23:00Z   
4  Technology news: A recent report by DigiTimes ...  2022-12-26T02:20:34Z   

   category sentiment  
0  business   Neutral  
1  business   Neutral  
2  business  Positive  
3  business   Neutral  
4  business  Positive

In [21]:
df.to_csv("data_news.csv")

#**Task** :: Find the topic of the article and the sentiment.

i was not able to get sufficient data to create model using as api as they have limit on data extraction on unpaid subscription thats why i am using openly availabe data 

In [22]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
nltk.download('punkt')
from wordcloud import WordCloud
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [29]:
#importing data set
dataset = pd.read_csv("BBC News Train.csv")

In [30]:
dataset.shape

(1490, 3)

In [31]:
dataset['Category'].value_counts() #category count

sport            346
business         336
politics         274
entertainment    273
tech             261
Name: Category, dtype: int64

In [32]:
target_category = dataset['Category'].unique()
print(target_category)

['business' 'tech' 'politics' 'sport' 'entertainment']


In [33]:
dataset['CategoryId'] = dataset['Category'].factorize()[0] #giving id to each category
dataset.head()

ArticleId                                               Text  Category  \
0       1833  worldcom ex-boss launches defence lawyers defe...  business   
1        154  german business confidence slides german busin...  business   
2       1101  bbc poll indicates economic gloom citizens in ...  business   
3       1976  lifestyle  governs mobile choice  faster  bett...      tech   
4        917  enron bosses in $168m payout eighteen former e...  business   

   CategoryId  
0           0  
1           0  
2           0  
3           1  
4           0

In [34]:
category = dataset[['Category', 'CategoryId']].drop_duplicates().sort_values('CategoryId')
category

Category  CategoryId
0       business           0
3           tech           1
5       politics           2
6          sport           3
7  entertainment           4

In [35]:
text = dataset["Text"]
text.head(10)

0    worldcom ex-boss launches defence lawyers defe...
1    german business confidence slides german busin...
2    bbc poll indicates economic gloom citizens in ...
3    lifestyle  governs mobile choice  faster  bett...
4    enron bosses in $168m payout eighteen former e...
5    howard  truanted to play snooker  conservative...
6    wales silent on grand slam talk rhys williams ...
7    french honour for director parker british film...
8    car giant hit by mercedes slump a slump in pro...
9    fockers fuel festive film chart comedy meet th...
Name: Text, dtype: object

In [36]:
def remove_tags(text):
  remove = re.compile(r'')
  return re.sub(remove, '', text)
  
dataset['Text'] = dataset['Text'].apply(remove_tags)


In [37]:
#removing special_char
def special_char(text):
  reviews = ''
  for x in text:
    if x.isalnum():
      reviews = reviews + x
    else:
      reviews = reviews + ' '
  return reviews
dataset['Text'] = dataset['Text'].apply(special_char)

In [38]:
#converting into lower
def convert_lower(text):
   return text.lower()
dataset['Text'] = dataset['Text'].apply(convert_lower)
dataset['Text'][1]

'german business confidence slides german business confidence fell in february knocking hopes of a speedy recovery in europe s largest economy   munich based research institute ifo said that its confidence index fell to 95 5 in february from 97 5 in january  its first decline in three months  the study found that the outlook in both the manufacturing and retail sectors had worsened  observers had been hoping that a more confident business sector would signal that economic activity was picking up    we re surprised that the ifo index has taken such a knock   said dz bank economist bernd weidensteiner   the main reason is probably that the domestic economy is still weak  particularly in the retail trade   economy and labour minister wolfgang clement called the dip in february s ifo confidence figure  a very mild decline   he said that despite the retreat  the index remained at a relatively high level and that he expected  a modest economic upswing  to continue   germany s economy grew 1 

In [39]:
#removing stopwords
def remove_stopwords(text):
  stop_words = set(stopwords.words('english'))
  words = word_tokenize(text)
  return [x for x in words if x not in stop_words]
dataset['Text'] = dataset['Text'].apply(remove_stopwords)

In [40]:
#lemmatization of text
def lemmatize_word(text):
  wordnet = WordNetLemmatizer()
  return " ".join([wordnet.lemmatize(word) for word in text])
dataset['Text'] = dataset['Text'].apply(lemmatize_word)
dataset['Text'][1]

'german business confidence slide german business confidence fell february knocking hope speedy recovery europe largest economy munich based research institute ifo said confidence index fell 95 5 february 97 5 january first decline three month study found outlook manufacturing retail sector worsened observer hoping confident business sector would signal economic activity picking surprised ifo index taken knock said dz bank economist bernd weidensteiner main reason probably domestic economy still weak particularly retail trade economy labour minister wolfgang clement called dip february ifo confidence figure mild decline said despite retreat index remained relatively high level expected modest economic upswing continue germany economy grew 1 6 last year shrinking 2003 however economy contracted 0 2 last three month 2004 mainly due reluctance consumer spend latest indication growth still proving elusive ifo president han werner sinn said improvement german domestic demand sluggish export

In [41]:
#defing x and y
x = dataset['Text']
y = dataset['CategoryId']

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
x = np.array(dataset.iloc[:,0].values)
y = np.array(dataset.CategoryId.values)
cv = CountVectorizer(max_features = 5000)
x = cv.fit_transform(dataset.Text).toarray()
print("X.shape = ",x.shape)
print("y.shape = ",y.shape)

X.shape =  (1490, 5000)
y.shape =  (1490,)


In [43]:
#splitting the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0, shuffle = True)
print(len(x_train))
print(len(x_test))

1043
447


In [44]:
#creating models
def Classifier_model(x_data,y_data):
  accuracy=[]
  precision=[]
  recall=[]
  f1=[]

  x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3,random_state=42)

  logistic_reg = LogisticRegression()
  ml = MultinomialNB(alpha=1.0,fit_prior=True)
  naive_bayes = GaussianNB()
  svm=SVC()
  dtree= DecisionTreeClassifier()
  rf = RandomForestClassifier(n_estimators=100 ,criterion='entropy' , random_state=0)
  KNN =KNeighborsClassifier(n_neighbors=10 , metric= 'minkowski' , p = 4)
  
  list = [logistic_reg,ml,naive_bayes,svm,dtree,rf,KNN]
  score = []
  for i in list:
    i.fit(x_train, y_train)
    pred = i.predict(x_test)
    print('\n')
    print(f'for {i} accuracy : {round(i.score(x_test, y_test)*100,2)} %')
    score.append(i.score(x_test, y_test))
    print(f'for {i}')    
    print(classification_report(y_test,pred))
    print(confusion_matrix(y_test,pred))
    print('\n')

    accuracy.append(accuracy_score(y_test,pred))
    precision.append(precision_score(y_test,pred,average='micro'))
    recall.append(recall_score(y_test,pred,average='micro'))
    f1.append(f1_score(y_test,pred,average='micro'))

  return accuracy,precision,recall,f1

In [45]:
acc,pre,re,F1=Classifier_model(x_train,y_train)



for LogisticRegression() accuracy : 95.85 %
for LogisticRegression()
              precision    recall  f1-score   support

           0       0.92      0.96      0.94        80
           1       0.98      0.92      0.95        53
           2       0.98      0.92      0.95        50
           3       0.96      0.99      0.97        68
           4       0.98      0.98      0.98        62

    accuracy                           0.96       313
   macro avg       0.96      0.96      0.96       313
weighted avg       0.96      0.96      0.96       313

[[77  0  1  2  0]
 [ 3 49  0  0  1]
 [ 3  1 46  0  0]
 [ 1  0  0 67  0]
 [ 0  0  0  1 61]]




for MultinomialNB() accuracy : 97.44 %
for MultinomialNB()
              precision    recall  f1-score   support

           0       0.99      0.94      0.96        80
           1       0.96      1.00      0.98        53
           2       0.92      0.94      0.93        50
           3       1.00      1.00      1.00        68
           4   

In [46]:
#creating dataframe for scores
performance=pd.DataFrame()
performance['Model']=['logistic_reg','Multinomial Naive Bayes','Gaussian Naive Bayes','Support Vector Classifer','Decision Tree Classifier','Random Forest','K Nearest Neighbour']
performance['Accuracy']=acc
performance['precision']=pre
performance['Recall']=re
performance['F1_score']=F1

In [53]:
performance

Model  Accuracy  precision    Recall  F1_score
0              logistic_reg  0.958466   0.958466  0.958466  0.958466
1   Multinomial Naive Bayes  0.974441   0.974441  0.974441  0.974441
2      Gaussian Naive Bayes  0.891374   0.891374  0.891374  0.891374
3  Support Vector Classifer  0.913738   0.913738  0.913738  0.913738
4  Decision Tree Classifier  0.811502   0.811502  0.811502  0.811502
5             Random Forest  0.942492   0.942492  0.942492  0.942492
6       K Nearest Neighbour  0.651757   0.651757  0.651757  0.651757

In [65]:
classifier =  MultinomialNB(alpha=1.0,fit_prior=True).fit(x_train, y_train)
classifier
y_pred = classifier.predict(x_test)

In [68]:
y_pred

array([4, 2, 3, 2, 3, 0, 0, 1, 4, 0, 3, 4, 2, 1, 3, 1, 0, 4, 1, 4, 1, 1,
       4, 1, 0, 0, 2, 3, 4, 1, 4, 3, 4, 4, 4, 0, 2, 0, 1, 1, 3, 0, 2, 0,
       3, 4, 3, 4, 1, 3, 2, 3, 4, 3, 3, 4, 4, 2, 3, 4, 3, 1, 3, 0, 3, 1,
       0, 1, 0, 4, 3, 3, 4, 1, 1, 2, 2, 2, 4, 1, 2, 1, 4, 4, 4, 3, 1, 0,
       0, 0, 0, 0, 3, 4, 2, 3, 0, 1, 4, 2, 4, 0, 0, 3, 2, 0, 3, 1, 2, 0,
       4, 4, 2, 2, 4, 4, 4, 4, 1, 2, 2, 0, 2, 3, 4, 1, 3, 3, 3, 3, 3, 3,
       0, 2, 2, 3, 3, 1, 3, 2, 0, 3, 2, 0, 4, 0, 1, 4, 2, 1, 3, 3, 3, 2,
       3, 3, 0, 4, 4, 0, 4, 0, 3, 0, 3, 3, 0, 2, 3, 0, 0, 4, 3, 4, 0, 4,
       1, 2, 0, 4, 1, 1, 1, 2, 1, 3, 0, 0, 4, 3, 2, 4, 2, 1, 0, 2, 2, 3,
       4, 2, 0, 3, 1, 4, 3, 0, 3, 4, 0, 1, 4, 0, 0, 1, 0, 2, 1, 4, 3, 2,
       4, 4, 1, 2, 0, 0, 2, 1, 4, 3, 3, 2, 2, 1, 2, 1, 4, 4, 1, 2, 4, 0,
       3, 3, 3, 1, 0, 2, 4, 2, 0, 1, 1, 0, 2, 3, 2, 2, 0, 4, 0, 1, 3, 1,
       3, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 3, 2, 4, 4, 1, 0, 1, 2, 4, 4, 3,
       3, 0, 0, 4, 1, 4, 3, 3, 1, 4, 4, 2, 1, 1, 4,